accordion:
  controls: arrow # arrow | plus-minus
  copyButton:
    ariaLabel: Copy page section link to clipboard
    successText: Copied page section link to clipboard
    symbol: §
  globalControls:
    collapseText: Collapse All
    expandText: Expand All

analytics:
  googleId: ''

bylineFormat: name-title # name | name-title | false

bibliography:
  displayOnPage: true
  displayShort: true
  heading: Bibliography

citations:
  divider: ', '
  popupStyle: text # text | icon

entryPage:
  sideBySide: false
  objectLinkText: View in Collection

epub:
  defaultCoverImage: 'epub-cover.png'
  outputDir: '_epub'

pdf:
  outputDir: '/_assets/downloads' # NB: This is within the site dir, the only time `_assets` is like that
  filename: 'publication'
  pagePDF: # FIXME: sectionPDF: paged: ? quirePaged?
    accessLinks:
      - header: true # Render a pdf access link in the header
        label: 'PDF'
      - footer: true # Render a pdf access link in the footer
        label: 'Download this page'
      - toc: true # Render a pdf access link in the toc
        label: 'PDF ↩'
    coverPage: true
    coverPageCitationStyle: 'mla' 
    output: false # FIXME: This may be more complex than needed? Just make the page PDF opt-in only in page frontmatter as designed? Do not produce the page PDF by default (only opt-in in RST frontmatter) -- this should be the default anyway?
    # websafe: true
    # cropsAndHashes: true
  publicationPDF:
    output: true # Produce the entire publication PDF -- FIXME: maybe just make this true / false directly
    # websafe: true
    # cropsAndHashes: true

footnotes:
  backlinkSymbol: '↩'

figures:
  assetDir: '/_assets/'
  enableModal: true
  imageDir: '/_assets/images'

licenseIcons: true

localization:
  defaultLocale: en-us

menuType: full # full | brief

navigation:
  nextButtonText: Next
  prevButtonText: Back

pageTitle:
  labelDivider: '. '

ref:
  sequenceTransition: 30

searchEnabled: true

tableOfContents:
  contributorDivider: ' — '
