# Javascript Node CircleCI 2.0 configuration file
#
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:trusty
        user: root
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Add test report directory
          command: mkdir -p ~/repo/test-results/jest
      - run:
          name: Add temporary directory to hold downloaded files
          command: mkdir -p /tmp
      - run:
          name: Install NodeJS and NPM
          command: |
            set +e             
            touch $BASH_ENV  
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install --lts

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Install Prince XML
          command: |
            wget -q -O /tmp/prince.deb https://www.princexml.com/download/prince_12.5-1_ubuntu14.04_amd64.deb
            dpkg -i /tmp/prince.deb
            rm /tmp/prince.deb
      - run:
          name: Install Pandoc
          command: |
            wget -q -O /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
            dpkg -i /tmp/pandoc.deb
            rm /tmp/pandoc.deb
      - run:
          name: Avoid hosts unknown for github
          command: |
            mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Install the quire-cli command
          command: npm install -g
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v3-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run Build Command
          command: npm run build
      - run:
          name: Run Quire Commands Test
          command: npm run circleci::test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
