# Javascript Node CircleCI 2.0 configuration file
#
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
        user: root
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Add test report directory
          command: mkdir -p ~/repo/test-results/jest
      - run:
          name: Add temporary directory to hold downloaded files
          command: mkdir -p /tmp
      - run:
          name: Install Prince XML Dependencies
          command: |
            apt-get update
            apt-get -y install libgif7 libjpeg-dev libjpeg62-turbo-dev
            wget -q -O /tmp/libjpeg-turbo8.deb http://mirrors.edge.kernel.org/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8_2.0.3-0ubuntu1_amd64.deb && dpkg -i /tmp/libjpeg-turbo8.deb && rm /tmp/libjpeg-turbo8.deb
            wget -q -O /tmp/libjpeg8.deb http://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg8-empty/libjpeg8_8c-2ubuntu8_amd64.deb && dpkg -i /tmp/libjpeg8.deb && rm /tmp/libjpeg8.deb
            wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb && dpkg -i /tmp/libpng12.deb && rm /tmp/libpng12.deb
            wget -q -O /tmp/libssl.deb http://security-cdn.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u11_amd64.deb && dpkg -i /tmp/libssl.deb && rm /tmp/libssl.deb
      - run:
          name: Install Prince XML
          command: |
            wget -q -O /tmp/prince.deb https://www.princexml.com/download/prince_12.5-1_ubuntu14.04_amd64.deb
            dpkg -i /tmp/prince.deb
            rm /tmp/prince.deb
      - run:
          name: Install Pandoc
          command: |
            wget -q -O /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
            dpkg -i /tmp/pandoc.deb
            rm /tmp/pandoc.deb
      - run:
          name: Avoid hosts unknown for github
          command: |
            mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Install the quire-cli command
          command: sudo npm install -g
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v3-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run Build Command
          command: npm run build
      - run:
          name: Run Quire Commands Test
          command: npm run circleci::test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
