---
name: Quire Bug Report
about: Tell us about the bug you encountered.
body:
- type: markdown
  attributes:
    value: Thank you for opening a new issue! Please search exisint gissues first to ensure the problem you've encountered has not been previously reported.
- type: markdown
  attributes:
    label: Description of issue
    required: true
    description: Tell us what happened.
- type: markdown
  attributes:
    label: Steps to reproduce
    required: true
    description: What steps did you take that led to the issue?
- type: markdown
  attributes:
    label: Expected behavior
    required: true
    description: What did you expect to happen?
- type: markdown
  attributes:
    label: Actual behavior
    required: true
    description: What actually happened?
- type: markdown
  attributes:
    label: Version numbers
    required: true
    description: Run `quire --version` and tell us what version you're currently running.
- type: markdown
  attributes:
    label: Text file of Terminal/Shell output
    description: Please attach a text file with the output when this error occured.
