---
name: Quire Bug Report
about: Tell us about the bug you encountered.
title: Application submitted by <replace with your name>
inputs:
- type: textarea
  attributes:
    label: Description of issue
    required: true
    placeholder:
    description: Tell us what happened.
- type: textarea
  attributes:
    label: Steps to reproduce
    required: true
    placeholder:
    description: What steps did you take that led to the issue?
- type: textarea
  attributes:
    label: Expected behavior
    required: true
    placeholder:
    description: What did you expect to happen?
- type: textarea
  attributes:
    label: Actual behavior
    required: true
    placeholder:
    description: What actually happened?
- type: textarea
  attributes:
    label: Version numbers
    required: true
    placeholder:
    description: Run `quire --version` and tell us what version you're currnetly running.
- type: textarea
  attributes:
    label: Text file of Terminal/Shell output
    required: 
    placeholder:
    description: Please attach a text file with the output when this error occured.
