---
name: Quire Bug Report
description: Create a report to help us improve Quire
labels: "bug"
issue_body: true
body:
- type: markdown
  attributes:
    value: |
      **Thank you for opening a new issue!** Before submitting your bug report, please search existing issues first to ensure the problem you've encountered has not been previously reported.
- type: textarea
  attributes:
    label: Describe the issue
    description: Tell us what happened.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: What steps did you take that led to the issue?
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      2. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: What did you expect to happen?
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual behavior
    description: What actually happened?
  validations:
    required: true
- type: textarea
  attributes:
    label: Version numbers
    description: Run `quire --version` and tell us what version you're currently running.
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      ## Supporting Information

      In the comments below, please attach the following files by dragging and dropping, and include any other information that may help us better understand your issue:

        - Save Terminal/Shell output and attach as a text file
        - Include screenshots showing the problem encountered
