name: Bug Report
description: Create a bug report to help us improve Quire
title: "[Bug]: "
labels: [bug]
assignees:
- erin-cecele
- geealbers
body:
- type: markdown
  attributes:
    value: |
      **Thank you for opening a new issue!** Before submitting your bug report, please search existing issues first to ensure the problem you've encountered has not been previously reported.
- type: textarea
  id: reproduce
  attributes:
    label: Steps to reproduce
    description: What steps did you take that led to the issue?
    placeholder: Being able to reproduce the issue will help us solve it, please be as specific as possible.
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: What did you expect to happen?
  validations:
    required: true
- type: textarea
  id: actual
  attributes:
    label: Actual behavior
    description: What actually happened?
  validations:
    required: true
- type: textarea
  id: version 
  attributes:
    label: Version numbers
    description: Sharing version numbers for the relevant programs will help us diagnose the issue. 
    placeholder: |
     Operating system (macOS/Windows)
     Operating system version
     Quire version (Run `quire --version`)
     Node version (Run `node --version`)
  validations:
    required: true
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
    - Firefox
    - Chrome
    - Safari
    - Microsoft Edge
- type: textarea
  id: logs
  attributes:
    label: Relevant Terminal/Shell output
    description: Please copy and paste any relevant log output. (If it's a preview issue run `quire preview --verbose`.)
    render: shell
- type: markdown
  attributes:
    value: |
      ## Supporting Information

      If you have additional files that would be useful in describing the issue (Terminal output, screenshots, Quire output files) attach them by dragging and dropping in the comments below.
