name: 🐛 Bug Report
description: Create a bug report to help us improve Quire
labels: [status:triage needed]
assignees:
- erin-cecele
- geealbers
body:
- type: markdown
  attributes:
    value: |
      # Thank you for opening a new issue! 
- type: checkboxes
  attributes:
    label: Before proceeding, check to make sure there isn’t an existing issue for this bug.
    description:
    options:
    - label: I have searched the existing issues and determined this is a new bug.
      required: true    
- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: Describe what you expected to happen had everything operated accordingly. 
  validations:
    required: true
- type: textarea
  id: actual
  attributes:
    label: Actual Behavior
    description: Describe what happened.
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: Steps to Reproduce
    description: Describe what steps you took that led to the issue. Please be as specific as possible.
    placeholder: Step 1... Step 2... Step 3... 
  validations:
    required: true
- type: textarea
  id: version 
  attributes:
    label: Quire Version Numbers
    description: Run `quire --version` to get the cli version number. In your project, open the `package.json` file to find the 11ty version number. 
    placeholder: 
  validations:
    required: true
- type: textarea
  id: version 
  attributes:
    label: Node Version Number
    description: Run `node --version` to get the Node version number. 
    placeholder: 
  validations:
    required: true
- type: textarea
  id: OS
  attributes:
    label: Operating Systen
    description: Let us know what Operating Systen you are working on? Please include the version number.
  validations:
    required: true
- type: textarea
  id: browsers
  attributes:
    label: Web Browser 
    description: Let us know what web browser you are working on (Chrome, Safari, Firefox, Microsoft Edge)? Please include the browser version number.
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Relevant Terminal/Shell Output
    description: Please copy and paste all relevant messaging from your Terminal/Shell.
    render: shell
- type: textarea
  id: supporting_info
  attributes:
    label: Supporting Information
    description: Please include any supporting information such as screenshots, output files, related issues, or potential workarounds.
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      # Once your report is submitted, it will automatically receive a “triage needed” label. The bug will then be reviewed by the Getty Quire team to decide if it will be selected for development. Labels will be applied to the issue based on type, status, and the core feature that is affected. We will comment on the issue and change the labels as we make progress have updates available and/or have workarounds. We may also tag you with questions or to request more information.

