---
name: Quire Bug Report
about: Create a report to help us improve Quire
labels: "bug"
issue_body: true
body:
- type: markdown
  attributes:
    value: |
      **Thank you for opening a new issue!**

      Before submitting your bug report, please search existing issues first, to ensure the problem you've encountered has not been previously reported.
- type: textarea
  attributes:
    label: Describe the issue
    description: Tell us what happened.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: What steps did you take that led to the issue?
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      2. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: What did you expect to happen?
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual behavior
    description: What actually happened?
  validations:
    required: true
- type: textarea
  attributes:
    label: Version numbers
    description: Run `quire --version` and tell us what version you're currently running.
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      ## Helpful Attachments

      Please be sure to add the following files and any additiuonal helpful information to the comments below to help us better understand your issue:

        - Save Terminal/Shell output and attach as a text file.
        - If useful, includes screenshots showing the problem
