blank_issues_enabled: false  # default: true
contact_links:
- name: 💬 Community Forum 
  url: https://github.com/thegetty/quire/discussions
  about: If you have questions, please post them in our GitHub Discussions forum.
- name: 📝 Contributing Guidelines
  url: https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md 
  about: Please take time to review our CONTRIBUTING.md file. 
- name: 🖥️ Website 
  url: https://quire.getty.edu
  about: Visit our website to learn more about Quire.


